//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyExpensive.Repositpry
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public string AmountType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AmountTypeImage { get; set; }
    }
}
